// <auto-generated />
using System;
using GeminiAsistanBackend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeminiAsistanBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615080309_ChangeTableColumns")]
    partial class ChangeTableColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.CihazKomutu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("CalisacakKod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calisacak_kod");

                    b.Property<string>("domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("domain", "target", "operation")
                        .IsUnique();

                    b.ToTable("cihaz_komutlari", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.IslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CevapMetni")
                        .HasColumnType("text")
                        .HasColumnName("cevap_metni");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("durum");

                    b.Property<string>("DuyulanSes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("duyulan_ses");

                    b.Property<int?>("KomutId")
                        .HasColumnType("integer")
                        .HasColumnName("komut_id");

                    b.Property<DateTime>("TarihSaat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih_saat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("raw_ai_json")
                        .HasColumnType("text")
                        .HasColumnName("raw_ai_json");

                    b.HasKey("Id");

                    b.HasIndex("KomutId");

                    b.ToTable("islem_loglari", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EklenmeTuru")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eklenme_turu");

                    b.Property<string>("TetikleyiciMetin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tetikleyici_metin");

                    b.Property<double?>("ai_confidence_score")
                        .HasColumnType("double precision")
                        .HasColumnName("ai_confidence_score");

                    b.HasKey("Id");

                    b.HasIndex("TetikleyiciMetin")
                        .IsUnique();

                    b.ToTable("ses_tetikleyicileri", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.TetikleyiciKomut", b =>
                {
                    b.Property<int>("TetikleyiciId")
                        .HasColumnType("integer")
                        .HasColumnName("tetikleyici_id");

                    b.Property<int>("KomutId")
                        .HasColumnType("integer")
                        .HasColumnName("komut_id");

                    b.HasKey("TetikleyiciId", "KomutId");

                    b.HasIndex("KomutId");

                    b.ToTable("tetikleyici_komut", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.IslemLog", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.CihazKomutu", "Komut")
                        .WithMany("IslemLoglari")
                        .HasForeignKey("KomutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Komut");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.TetikleyiciKomut", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.CihazKomutu", "Komut")
                        .WithMany("TetikleyiciKomutlari")
                        .HasForeignKey("KomutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", "Tetikleyici")
                        .WithMany("TetikleyiciKomutlari")
                        .HasForeignKey("TetikleyiciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komut");

                    b.Navigation("Tetikleyici");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.CihazKomutu", b =>
                {
                    b.Navigation("IslemLoglari");

                    b.Navigation("TetikleyiciKomutlari");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", b =>
                {
                    b.Navigation("TetikleyiciKomutlari");
                });
#pragma warning restore 612, 618
        }
    }
}
