// <auto-generated />
using System;
using GeminiAsistanBackend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeminiAsistanBackend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706121638_updateSesTetikleyicileri")]
    partial class updateSesTetikleyicileri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.AsistanYanit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<string>("asistan_yanit")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("asistan_yanit");

                    b.Property<int?>("cihaz_komut_id")
                        .HasColumnType("integer")
                        .HasColumnName("cihaz_komut_id");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("feedback")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("feedback");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("yanitTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("yanit_turu");

                    b.HasKey("id");

                    b.HasIndex("cihaz_komut_id");

                    b.ToTable("asistan_yanit", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.CihazKomutu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("CalisacakKod")
                        .HasColumnType("text")
                        .HasColumnName("calisacak_kod");

                    b.Property<string>("domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("target")
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("cihaz_komutlari", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.EgitimDataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("sesTetikleyici_id")
                        .HasColumnType("integer");

                    b.Property<string>("tetikleyici_metin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tetikleyici_metin");

                    b.Property<int>("type_num")
                        .HasColumnType("integer")
                        .HasColumnName("type_num");

                    b.HasKey("Id");

                    b.HasIndex("sesTetikleyici_id");

                    b.HasIndex("tetikleyici_metin")
                        .IsUnique();

                    b.ToTable("egitim_dataset", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.IslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CevapMetni")
                        .HasColumnType("text")
                        .HasColumnName("cevap_metni");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("durum");

                    b.Property<string>("DuyulanSes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("duyulan_ses");

                    b.Property<int?>("KomutId")
                        .HasColumnType("integer")
                        .HasColumnName("komut_id");

                    b.Property<DateTime>("TarihSaat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tarih_saat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("raw_ai_json")
                        .HasColumnType("text")
                        .HasColumnName("raw_ai_json");

                    b.HasKey("Id");

                    b.HasIndex("KomutId");

                    b.ToTable("islem_loglari", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.RedmineEgitimDataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("redmine_tetikleyici_metin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redmine_tetikleyici_metin");

                    b.Property<int>("sesTetikleyici_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("redmine_tetikleyici_metin")
                        .IsUnique();

                    b.HasIndex("sesTetikleyici_id");

                    b.ToTable("redmine_egitim_dataset", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EklenmeTuru")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eklenme_turu");

                    b.Property<string>("TetikleyiciMetin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tetikleyici_metin");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("llm_confidence_score")
                        .HasColumnType("double precision")
                        .HasColumnName("llm_confidence_score");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TetikleyiciMetin")
                        .IsUnique();

                    b.ToTable("ses_tetikleyicileri", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.TetikleyiciKomut", b =>
                {
                    b.Property<int>("TetikleyiciId")
                        .HasColumnType("integer")
                        .HasColumnName("tetikleyici_id");

                    b.Property<int>("KomutId")
                        .HasColumnType("integer")
                        .HasColumnName("komut_id");

                    b.HasKey("TetikleyiciId", "KomutId");

                    b.HasIndex("KomutId");

                    b.ToTable("tetikleyici_komut", (string)null);
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.AsistanYanit", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.CihazKomutu", "cihazkomutu")
                        .WithMany("AsistanYanitlar")
                        .HasForeignKey("cihaz_komut_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("cihazkomutu");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.EgitimDataset", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", "SesTetikleyicisi")
                        .WithMany("EgitimDatasetleri")
                        .HasForeignKey("sesTetikleyici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesTetikleyicisi");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.IslemLog", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.CihazKomutu", "Komut")
                        .WithMany("IslemLoglari")
                        .HasForeignKey("KomutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Komut");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.RedmineEgitimDataset", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", "sesTetikleyicisi")
                        .WithMany("RedmineEgitimDatasets")
                        .HasForeignKey("sesTetikleyici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sesTetikleyicisi");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.TetikleyiciKomut", b =>
                {
                    b.HasOne("GeminiAsistanBackend.Domain.Entities.CihazKomutu", "Komut")
                        .WithMany("TetikleyiciKomutlari")
                        .HasForeignKey("KomutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", "Tetikleyici")
                        .WithMany("TetikleyiciKomutlari")
                        .HasForeignKey("TetikleyiciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komut");

                    b.Navigation("Tetikleyici");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.CihazKomutu", b =>
                {
                    b.Navigation("AsistanYanitlar");

                    b.Navigation("IslemLoglari");

                    b.Navigation("TetikleyiciKomutlari");
                });

            modelBuilder.Entity("GeminiAsistanBackend.Domain.Entities.SesTetikleyicisi", b =>
                {
                    b.Navigation("EgitimDatasetleri");

                    b.Navigation("RedmineEgitimDatasets");

                    b.Navigation("TetikleyiciKomutlari");
                });
#pragma warning restore 612, 618
        }
    }
}
